### PR TITLE
Don't link libraries directly, only the executable.

### PR DESCRIPTION
**Pull request by kainjow**
This fixes excessive warnings resulting in a failed build when using Xcode generator on OS X.

### CODE REVIEW

**Comment by bel2125** [comment]
In this case, 50% of the gcc builds fail, while it seems OK for clang:
https://travis-ci.org/civetweb/civetweb/builds/124894319

There seems to be some problem with the dl library now:
https://travis-ci.org/civetweb/civetweb/jobs/124894324#L447

**Comment by kainjow** [comment]
Interesting. Ok, I'll look at this again.

**Comment by kainjow** [comment]
Looks like the GCC ENABLE_SSL=YES ones are failing, which makes sense since they load the lib dynamically.

**Comment by bel2125** [comment]
How should we continue here:
If the ['target_linked_library'](https://cmake.org/cmake/help/v3.3/command/target_link_libraries.html) lines are removed, the builds with OpenSSL libraries fail, otherwise they work.
I don't know the "Xcode generator on OS X" problem, since I neither know Xcode nor have an OSX system to test, but I can not merge this commit if the OpenSSL builds/tests on Travis fail.

**Comment by kainjow** [comment]
I borked the rebase of this branch. I want to get a better understanding of the error, so I will just abandon this for now and look into it later.

**Pull request closed without merging**
