### PR TITLE
discard unread data if handled by begin_request()

### PR DESCRIPTION
**Pull request by yehudasa**
Signed-off-by: Yehuda Sadeh <yehuda@redhat.com>

### CODE REVIEW

**Comment by bel2125** [comment]
The Travis CI fails for this PR - maybe #345 strikes again. I will check it.

**Comment by bel2125** [comment]
Wouldn't this cause problems, if `keep_alive` is `yes`, and you use request pipe-lining?

**Comment by yehudasa** [comment]
@bel2125 this fixes an issue when keel_alive is yes. The problem is that if we don't drain the request, and begin_request() didn't read all the data off the pipe, the next request that will be handled will be broken

**Comment by bel2125** [comment]
It seems all OSX builds are failing, but I cannot imagine how adding this line can cause errors like 
```
/System/Library/Frameworks/Kernel.framework/Headers/sys/_types/_mach_port_t.h:49:30: error: typedef redefinition with different types ('__darwin_mach_port_t' (aka 'unsigned int') vs 'ipc_port_t' (aka 'struct ipc_port *'))

typedef __darwin_mach_port_t mach_port_t;
```
or
```
/Users/travis/build/civetweb/civetweb/test/../src/civetweb.c:3899:20: error: use of undeclared identifier 'errno'

strerror(ERRNO));
```
(logs of build 152: https://travis-ci.org/civetweb/civetweb/jobs/165652355)

Probably Travis CI changed something in the OSX build environment since the last build 751 (https://travis-ci.org/civetweb/civetweb/builds/163312168).

I think I will first repeat build 751.

**Comment by bel2125** [comment]
After restarting Travis CI build 751 (https://travis-ci.org/civetweb/civetweb/builds/163312168), it seems now all OSX builds fail as well. So Travis changed something in the OSX build environment.

**Pull request merged**
