### PR TITLE
make SOMAXCONN configurable (fix 775)

### PR DESCRIPTION
**Pull request by chardan**
Adds a configurable "max_connections" parameter that allows user-tuneable SOMAXCONN.

See-also:
https://github.com/civetweb/civetweb/issues/775

### CODE REVIEW

**Comment by bel2125** [comment]
The name "max_connections" seems to cause confusion, since it's not a limit for the *maximum number of (active) connections* - both, the Linux API and Windows API documentation name for the parameter seems to be "backlog" (http://man7.org/linux/man-pages/man2/listen.2.html, https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-listen). I will have to rename this parameter for the upcoming release (it's not yet in a released version, and not yet documented in UserManual.md).

Currently there are 3 connection "backlog/queues/limit/..(whatever) **stages**": 
 1) The first one is this one ("backlog" ... name to be defined), maintained by the operating system
 2) The second one is "connection_queue" (socket accepted, but not yet dispatched to a worker thread)
 3) Finally there are "num_threads" worker threads. 
Only after all three **stages** (or whatever we call it) are full, further connections attempts need to be ignored (so, this sum would be the *maximum number of (active) connections* ("max_connections"?) limit. The first "stage" needs a new (less confusing) name - maybe "listen_backlog"?

**Comment by chardan** [comment]
@bel2125 Hi, thanks for the thoughtful comment-- that's a great explanation and I see the source of confusion. "listen_backlog" seems ok to me, as would "max_pending_connections". Any preference between them (or another suggestion)?

**Comment by bel2125** [comment]
I tried to explain them here:

https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#num_threads-50

https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#listen_backlog-200

https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md#connection_queue-20

And I also increased the default value from 100 to 200, since this seems to be some minimum for Windows (see SOMAXCONN_HINT, https://docs.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-listen)

**Comment by chardan** [comment]
@bel2125 +1, looks good to me!

**Pull request merged**
