### PR TITLE
Add install targets for headers and libraries.

### PR DESCRIPTION
**Pull request by hojalot**

### CODE REVIEW

**Comment by bel2125** [comment]
Thanks.
I assume you tested it for one or more Linux distributions?
Could you add a short description for what systems this is supposed to work?

**Comment by hojalot** [comment]
Yes, I tested under Ubuntu 17.10 by building an application that includes CivetServer.h and links against the static lib.

I assume that the added install targets only apply to Linux systems, like docs/Building.md mentions in the "Using Make" section.

**Comment by bel2125** [comment]
Thank you for your contribution. Merged.

For future pull requests (... you are welcome to contribute something in future ...) "please provide a description for every pull request" (as mentioned in the [contribution](https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md) docs ;-) )

**Comment by hojalot** [comment]
Does the description go in the pull request, the commit message or both?

**Comment by bel2125** [comment]
You can add a description in the commit - but this is independent from the description here in the pull request.
I'm just asking for a description, because I do a quick review of all pull requests: First I check title and description to get an idea of the problem/enhancement that is supposed solved with the pull request. Then I check if the "files changed" are suitable for this purpose. And I check the files changed, if it could cause new issues.
If there is no description, I can just guess from the changed files what should be solved by the pull request.

That's why I added "*Please provide a description for every pull request*" to the [Contribution.md](https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md) documentation.

**Pull request merged**
