### PR TITLE
Add option for building civetweb without timegm().

### PR DESCRIPTION
**Pull request by c-mauderer**
Using the NO_TIMEGM option disables the caching feature. Civetweb will not be able to detect a unchanged file. On the other hand it allows to build civetweb on systems that don't implement timegm().

### CODE REVIEW

**Comment by bel2125** [comment]
I agree to this patch.
Could you still tell me what system without timegm() you mean?

Alternatively, I got the hint that it could be possible to use the timegm implementation of the musl project - see this comment: https://github.com/civetweb/civetweb/issues/278#issuecomment-199116279
musl uses an MIT licence, so it would be possible to integrate a function from there in civetweb.

I did not yet decide about integrating this piece of code.

**Comment by c-mauderer** [comment]
I'm currently trying to replace the old version of mongoose that is integrated into RTEMS (https://www.rtems.org/) with the latest version of civetweb. RTEMS is using newlib for it's standard-C-library and there is currently not timegm implemented in newlib (at least not for anything but cygwin).

My first approach was to replace timegm with standard POSIX functions like for example suggested in the man page of timegm (http://linux.die.net/man/3/timegm) but it seems that there is really no easy way to do this in a thread save way. So I just disabled this feature as a temporary fix and noted down that we might have to implement timegm for RTEMS in the long term.

But even if RTEMS sometimes gets a timegm, I think optionally disabling this function can still be useful for other embedded operating systems.

**Comment by bel2125** [comment]
Probably having an alternative implementation for `timegm` is useful for RTEMS and other (embedded) operating systems as well. 
[musl](http://www.musl-libc.org/) could be an option, it has a [timegm implementation](http://git.musl-libc.org/cgit/musl/tree/src/time/timegm.c), with two helper functions ([tm_to_secs](http://git.musl-libc.org/cgit/musl/tree/src/time/__tm_to_secs.c), [secs_to_tm](http://git.musl-libc.org/cgit/musl/tree/src/time/__secs_to_tm.c)).
It probably does not handle leap seconds, so I would not take this as a general replacement if there is an operating system timegm function that does handle leap seconds.

**Comment by c-mauderer** [comment]
I think a correct time calculation is not really easy. For a (possible future) implementation of the timegm function in RTEMS, I would try to use the one from freebsd: https://github.com/freebsd/freebsd/blob/master/contrib/tzcode/stdtime/localtime.c#L2136
The helper functions that are used in FreeBSD (time1 and time2) are a bit more complex than the ones in musl. But I would expect that they can handle most cases.

**Comment by bel2125** [comment]
The advantage of musl is the MIT license. Thus, it would be possible to copy the musl code here.

The FreeBSD code has at least some parts with 4-clause BSD license (https://github.com/freebsd/freebsd/blob/master/COPYRIGHT#L39) - this can not be added here.
So if the FreeBSD implementation is used, civetweb would just leave an undefined reference, and it is up to the user to link it with a proper implementation.

**Comment by c-mauderer** [comment]
Sorry for not answering earlier. I'm a little busy right now.

As far as I can tell, the FreeBSD-code is based on an older version of the IANA time zone database (http://www.iana.org/time-zones/repository/releases/tzcode2016d.tar.gz). This code is (with three exceptions) public domain according to the LICENSE file packed into the zip. Eventually this could be a better alternative to the less exact musl?

On the other hand, the "localtime.c" in this package has 2271 lines of code. So it's not really the smallest package. What do you think?

**Comment by bel2125** [comment]
I think my preferred implementation is this one:

```
time_t sec_since_epoch[69][12] =
{0, 2678400, 5097600, 7776000, 10368000, 13046400, 15638400, 18316800, 20995200, 23587200, 26265600, 28857600},
{31536000, 34214400, 36633600, 39312000, 41904000, 44582400, 47174400, 49852800, 52531200, 55123200, 57801600, 60393600},
{63072000, 65750400, 68256000, 70934400, 73526400, 76204800, 78796800, 81475200, 84153600, 86745600, 89424000, 92016000},
{94694400, 97372800, 99792000, 102470400, 105062400, 107740800, 110332800, 113011200, 115689600, 118281600, 120960000, 123552000},
{126230400, 128908800, 131328000, 134006400, 136598400, 139276800, 141868800, 144547200, 147225600, 149817600, 152496000, 155088000},
{157766400, 160444800, 162864000, 165542400, 168134400, 170812800, 173404800, 176083200, 178761600, 181353600, 184032000, 186624000},
{189302400, 191980800, 194486400, 197164800, 199756800, 202435200, 205027200, 207705600, 210384000, 212976000, 215654400, 218246400},
{220924800, 223603200, 226022400, 228700800, 231292800, 233971200, 236563200, 239241600, 241920000, 244512000, 247190400, 249782400},
{252460800, 255139200, 257558400, 260236800, 262828800, 265507200, 268099200, 270777600, 273456000, 276048000, 278726400, 281318400},
{283996800, 286675200, 289094400, 291772800, 294364800, 297043200, 299635200, 302313600, 304992000, 307584000, 310262400, 312854400},
{315532800, 318211200, 320716800, 323395200, 325987200, 328665600, 331257600, 333936000, 336614400, 339206400, 341884800, 344476800},
{347155200, 349833600, 352252800, 354931200, 357523200, 360201600, 362793600, 365472000, 368150400, 370742400, 373420800, 376012800},
{378691200, 381369600, 383788800, 386467200, 389059200, 391737600, 394329600, 397008000, 399686400, 402278400, 404956800, 407548800},
{410227200, 412905600, 415324800, 418003200, 420595200, 423273600, 425865600, 428544000, 431222400, 433814400, 436492800, 439084800},
{441763200, 444441600, 446947200, 449625600, 452217600, 454896000, 457488000, 460166400, 462844800, 465436800, 468115200, 470707200},
{473385600, 476064000, 478483200, 481161600, 483753600, 486432000, 489024000, 491702400, 494380800, 496972800, 499651200, 502243200},
{504921600, 507600000, 510019200, 512697600, 515289600, 517968000, 520560000, 523238400, 525916800, 528508800, 531187200, 533779200},
{536457600, 539136000, 541555200, 544233600, 546825600, 549504000, 552096000, 554774400, 557452800, 560044800, 562723200, 565315200},
{567993600, 570672000, 573177600, 575856000, 578448000, 581126400, 583718400, 586396800, 589075200, 591667200, 594345600, 596937600},
{599616000, 602294400, 604713600, 607392000, 609984000, 612662400, 615254400, 617932800, 620611200, 623203200, 625881600, 628473600},
{631152000, 633830400, 636249600, 638928000, 641520000, 644198400, 646790400, 649468800, 652147200, 654739200, 657417600, 660009600},
{662688000, 665366400, 667785600, 670464000, 673056000, 675734400, 678326400, 681004800, 683683200, 686275200, 688953600, 691545600},
{694224000, 696902400, 699408000, 702086400, 704678400, 707356800, 709948800, 712627200, 715305600, 717897600, 720576000, 723168000},
{725846400, 728524800, 730944000, 733622400, 736214400, 738892800, 741484800, 744163200, 746841600, 749433600, 752112000, 754704000},
{757382400, 760060800, 762480000, 765158400, 767750400, 770428800, 773020800, 775699200, 778377600, 780969600, 783648000, 786240000},
{788918400, 791596800, 794016000, 796694400, 799286400, 801964800, 804556800, 807235200, 809913600, 812505600, 815184000, 817776000},
{820454400, 823132800, 825638400, 828316800, 830908800, 833587200, 836179200, 838857600, 841536000, 844128000, 846806400, 849398400},
{852076800, 854755200, 857174400, 859852800, 862444800, 865123200, 867715200, 870393600, 873072000, 875664000, 878342400, 880934400},
{883612800, 886291200, 888710400, 891388800, 893980800, 896659200, 899251200, 901929600, 904608000, 907200000, 909878400, 912470400},
{915148800, 917827200, 920246400, 922924800, 925516800, 928195200, 930787200, 933465600, 936144000, 938736000, 941414400, 944006400},
{946684800, 949363200, 951868800, 954547200, 957139200, 959817600, 962409600, 965088000, 967766400, 970358400, 973036800, 975628800},
{978307200, 980985600, 983404800, 986083200, 988675200, 991353600, 993945600, 996624000, 999302400, 1001894400, 1004572800, 1007164800},
{1009843200, 1012521600, 1014940800, 1017619200, 1020211200, 1022889600, 1025481600, 1028160000, 1030838400, 1033430400, 1036108800, 1038700800},
{1041379200, 1044057600, 1046476800, 1049155200, 1051747200, 1054425600, 1057017600, 1059696000, 1062374400, 1064966400, 1067644800, 1070236800},
{1072915200, 1075593600, 1078099200, 1080777600, 1083369600, 1086048000, 1088640000, 1091318400, 1093996800, 1096588800, 1099267200, 1101859200},
{1104537600, 1107216000, 1109635200, 1112313600, 1114905600, 1117584000, 1120176000, 1122854400, 1125532800, 1128124800, 1130803200, 1133395200},
{1136073600, 1138752000, 1141171200, 1143849600, 1146441600, 1149120000, 1151712000, 1154390400, 1157068800, 1159660800, 1162339200, 1164931200},
{1167609600, 1170288000, 1172707200, 1175385600, 1177977600, 1180656000, 1183248000, 1185926400, 1188604800, 1191196800, 1193875200, 1196467200},
{1199145600, 1201824000, 1204329600, 1207008000, 1209600000, 1212278400, 1214870400, 1217548800, 1220227200, 1222819200, 1225497600, 1228089600},
{1230768000, 1233446400, 1235865600, 1238544000, 1241136000, 1243814400, 1246406400, 1249084800, 1251763200, 1254355200, 1257033600, 1259625600},
{1262304000, 1264982400, 1267401600, 1270080000, 1272672000, 1275350400, 1277942400, 1280620800, 1283299200, 1285891200, 1288569600, 1291161600},
{1293840000, 1296518400, 1298937600, 1301616000, 1304208000, 1306886400, 1309478400, 1312156800, 1314835200, 1317427200, 1320105600, 1322697600},
{1325376000, 1328054400, 1330560000, 1333238400, 1335830400, 1338508800, 1341100800, 1343779200, 1346457600, 1349049600, 1351728000, 1354320000},
{1356998400, 1359676800, 1362096000, 1364774400, 1367366400, 1370044800, 1372636800, 1375315200, 1377993600, 1380585600, 1383264000, 1385856000},
{1388534400, 1391212800, 1393632000, 1396310400, 1398902400, 1401580800, 1404172800, 1406851200, 1409529600, 1412121600, 1414800000, 1417392000},
{1420070400, 1422748800, 1425168000, 1427846400, 1430438400, 1433116800, 1435708800, 1438387200, 1441065600, 1443657600, 1446336000, 1448928000},
{1451606400, 1454284800, 1456790400, 1459468800, 1462060800, 1464739200, 1467331200, 1470009600, 1472688000, 1475280000, 1477958400, 1480550400},
{1483228800, 1485907200, 1488326400, 1491004800, 1493596800, 1496275200, 1498867200, 1501545600, 1504224000, 1506816000, 1509494400, 1512086400},
{1514764800, 1517443200, 1519862400, 1522540800, 1525132800, 1527811200, 1530403200, 1533081600, 1535760000, 1538352000, 1541030400, 1543622400},
{1546300800, 1548979200, 1551398400, 1554076800, 1556668800, 1559347200, 1561939200, 1564617600, 1567296000, 1569888000, 1572566400, 1575158400},
{1577836800, 1580515200, 1583020800, 1585699200, 1588291200, 1590969600, 1593561600, 1596240000, 1598918400, 1601510400, 1604188800, 1606780800},
{1609459200, 1612137600, 1614556800, 1617235200, 1619827200, 1622505600, 1625097600, 1627776000, 1630454400, 1633046400, 1635724800, 1638316800},
{1640995200, 1643673600, 1646092800, 1648771200, 1651363200, 1654041600, 1656633600, 1659312000, 1661990400, 1664582400, 1667260800, 1669852800},
{1672531200, 1675209600, 1677628800, 1680307200, 1682899200, 1685577600, 1688169600, 1690848000, 1693526400, 1696118400, 1698796800, 1701388800},
{1704067200, 1706745600, 1709251200, 1711929600, 1714521600, 1717200000, 1719792000, 1722470400, 1725148800, 1727740800, 1730419200, 1733011200},
{1735689600, 1738368000, 1740787200, 1743465600, 1746057600, 1748736000, 1751328000, 1754006400, 1756684800, 1759276800, 1761955200, 1764547200},
{1767225600, 1769904000, 1772323200, 1775001600, 1777593600, 1780272000, 1782864000, 1785542400, 1788220800, 1790812800, 1793491200, 1796083200},
{1798761600, 1801440000, 1803859200, 1806537600, 1809129600, 1811808000, 1814400000, 1817078400, 1819756800, 1822348800, 1825027200, 1827619200},
{1830297600, 1832976000, 1835481600, 1838160000, 1840752000, 1843430400, 1846022400, 1848700800, 1851379200, 1853971200, 1856649600, 1859241600},
{1861920000, 1864598400, 1867017600, 1869696000, 1872288000, 1874966400, 1877558400, 1880236800, 1882915200, 1885507200, 1888185600, 1890777600},
{1893456000, 1896134400, 1898553600, 1901232000, 1903824000, 1906502400, 1909094400, 1911772800, 1914451200, 1917043200, 1919721600, 1922313600},
{1924992000, 1927670400, 1930089600, 1932768000, 1935360000, 1938038400, 1940630400, 1943308800, 1945987200, 1948579200, 1951257600, 1953849600},
{1956528000, 1959206400, 1961712000, 1964390400, 1966982400, 1969660800, 1972252800, 1974931200, 1977609600, 1980201600, 1982880000, 1985472000},
{1988150400, 1990828800, 1993248000, 1995926400, 1998518400, 2001196800, 2003788800, 2006467200, 2009145600, 2011737600, 2014416000, 2017008000},
{2019686400, 2022364800, 2024784000, 2027462400, 2030054400, 2032732800, 2035324800, 2038003200, 2040681600, 2043273600, 2045952000, 2048544000},
{2051222400, 2053900800, 2056320000, 2058998400, 2061590400, 2064268800, 2066860800, 2069539200, 2072217600, 2074809600, 2077488000, 2080080000},
{2082758400, 2085436800, 2087942400, 2090620800, 2093212800, 2095891200, 2098483200, 2101161600, 2103840000, 2106432000, 2109110400, 2111702400},
{2114380800, 2117059200, 2119478400, 2122156800, 2124748800, 2127427200, 2130019200, 2132697600, 2135376000, 2137968000, 2140646400, 2143238400}
};

return sec_since_epoch[tm_year-70][tm_mon] + (tm_mday-1)*24*60*60 + tm_hour*60*60 + tm_min*60 + tm_sec
```

This is a table of the seconds since epoch of the first of every month from 1970 to 2038 (could be more if sizeof(time_t)>4).

**Comment by c-mauderer** [comment]
This implementation is definitely fast and easy to read. So it might be a good starting point. I'm not sure if a calculation wouldn't be smaller in code size but let's just ignore that. By the way: The table you posted currently does not handle leap seconds. But it should be able to do it in an approximation. It can be correct at the beginning of each month.

A bigger problem could be the end year: Some embedded systems run quite a while (for example industrial controlling systems or satellites) so 2038 doesn't seem that far. I don't think, that it is a problem if the system isn't accurate after a given year but it mustn't crash. So checking the indices for a limit would be necessary. Another start year for getting accurate times for some more years in the future could be worth a thought too. I would expect that the past isn't that relevant.

So if you are OK with it, I would try to write a solution along the following (just a concept. I would align it with your coding style):

    #define START_YEAR 116
    #define NR_OF_YEARS 100
    #define MONTHS_PER_YEAR 12
    time_t sec_since_epoch[NR_OF_YEARS][MONTHS_PER_YEAR] = {
        /* fill in a (generated?) list with first seconds of the months */
    }

    if(tm_year < START_YEAR || tm_year >= START_YEAR + NR_OF_YEARS) {
        /* Return an approximation. */
        return tm_sec + tm_min*60 + tm_hour*3600 + tm_yday*86400 +
            (tm_year-70)*31536000 + ((tm_year-69)/4)*86400 -
            ((tm_year-1)/100)*86400 + ((tm_year+299)/400)*86400;
    } else {
        return sec_since_epoch[tm_year-START_YEAR][tm_mon] + (tm_mday-1)*24*60*60 + tm_hour*60*60 + tm_min*60 + tm_sec;
    }

I would have to put some more thoughts in it and might check the month index too.

I took the approximation from http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_15
The formula should be to short and obvious to have any copyright. Anyway, the copyright should be compatible too: http://pubs.opengroup.org/onlinepubs/9699919799/frontmatter/notice.html

**Comment by bel2125** [comment]
> A bigger problem could be the end year: Some embedded systems run quite a while (for example industrial controlling systems or satellites) so 2038 doesn't seem that far. 

I know.

But 2038 is the limit for a 32 bit time_t with 1970-01-01 = 0, just like usual for most systems.
This is not a specific civetweb limitation but the [Y2038 bug](wikw ).
You have to use a 64 bit time_t in order to use dates after 2038 (this is what all desktop systems do).
Otherwise you have to either use a different epoch, e.g. 2016-01-01 = 0, or define time_t as unsigned. Both would mean you have to get a special C library.

> Another start year for getting accurate times for some more years in the future could be worth a thought too. I would expect that the past isn't that relevant.

That's exactly what I meant with shifting the epoch.
But I think you have to replace all standard C functions working with a time_t data type in order to get this working. Changing only `timegm()` to use a different `time_t` will cause some problems with `time()`, `gmtime()`, `localtime()`, `mktime()`, ... all functions have to work with the same definition of `time_t`. If you re-implement one of them, you have to re-implement all of them.

> So if you are OK with it, I would try to write a solution along the following

As stated above, I think shifting the epoch will require to exchange several other C standard library functions as well. I might be wrong, but if I'm right, we need to find a different solution.

**Comment by bel2125** [comment]
[The formula from The Open Group](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_15) uses `tm_yday`:
```
    return tm_sec + tm_min*60 + tm_hour*3600 + tm_yday*86400 +
        (tm_year-70)*31536000 + ((tm_year-69)/4)*86400 -
        ((tm_year-1)/100)*86400 + ((tm_year+299)/400)*86400;
```
The way we use `timegm`, we know `tm_mon` and `tm_mday`, but not `tm_yday`. So `tm_yday` has to be calculated first.

**Comment by c-mauderer** [comment]
I'm aware where the 2038 problem comes from. I thought more along the line of splitting the table depending on the size of time_t. On a system with a 64Bit time_t, the table would reach beyond 2038. On all other systems, it would just stop there and maybe issue a warning. This should be possible with preprocessor directives.

I agree that shifting the epoche wouldn't be a good idea. If we would take systems with a shifted epoche in account, we would get a problem with any calculation outside of the c library. So every patch that provides a timegm() has to assume a "standard" time_t representation as seconds since 1970. At least I wouldn't know another way.

I thought more along the way of cutting of the first part of the table to save memory.

**Comment by bel2125** [comment]
> By the way: The table you posted currently does not handle leap seconds.

Interesting. Then the script I used does not know leap seconds. I did not check this in advance, since I posted it here only as a concept.
Leap seconds are one of the reasons why I wanted to use a table.

It seems leap seconds are often avoided or implemented differently on purpose: Some servers do not do a leap second, but for one day every second takes 1.000011574 seconds, some bank servers move the leap second to maintenance phases on bank holidays, ...
But since leap seconds are not known in advance (according to [Wikipedia](https://en.wikipedia.org/wiki/Leap_second#Insertion_of_leap_seconds) they are announced only six month in advance), one can not build a table for several years into the future.

> I thought more along the way of cutting of the first part of the table to save memory.

If leap seconds can not be calculated in advance, probably a table with the seconds for every first of March would do. But without leap seconds, that's not too hard to calculate either.

If leap seconds are not known in advance, a system without regular updates every some months and/or an external time server will not be able to take leap seconds into account.

**Comment by c-mauderer** [comment]
Sound like the problem with leap seconds can't be easily solved. So falling back to the solution from musl like you suggested at the beginning would be a good solution.

If you want, I can write the patch. From the current code style I would expect that the code should go in an .inl? I wouldn't touch the coding style of the musl source so that a future update is simpler to integrate. Is that OK for you?

And having to few experience with github: Is there a way to just update this pull-request or would I have to close it and create a new one?

**Comment by bel2125** [comment]
After some discussion we came to the conclusion that it is not really wise to implement `timegm` in the civetweb source. Leap seconds are one of the reasons it should be avoided. If you do have a C runtime that does implement leap seconds in `gmtime` but you do not implement it in `timegm`, you run in troubles. The same is true if your C runtime does not implement leap seconds (it seems `msvcrt` does not), but you do implement it in `timegm` - whatever you do, it will be wrong for 50% of the systems.
If `x != timegm(gmtime(x))`, unchanged files might be considered as changed or changed files as unchanged - nobody knows for sure what happens, and bugs will probably be not reproducible.
You need to have a `timegm` implementation, that does exactly fit the `gmtime` of your C runtime.
Since I do not know every C runtime, and the C runtimes behave differently on different systems, this problem can not be solved in CivetWeb.
It is also not known in advance when leap seconds are going to happen in ~20 years (whatever the lifetime of your embedded system is supposed to be). For Linux, leap seconds can be included by Linux system updated. You would have to make sure a Linux system update would also update a `timegm` implementation. Ok, ...Linux has a timegm function. But this similar update scenario also has to be considered for your embedded system. And even if you find a scenario for *your* system, it needs to work for all other (embedded) system using civetweb as well.
The only solution to implement a missing `y = timegm(x)` would be to call `gmtime(y)` iteratively with varying `y`, until you get `x` (iteratively solve the inverse problem). This is stable with respect to leap seconds, but its far from efficient.

I think CivetWeb has to rely on `timegm` being implemented externally.
If it does not exist in the C runtime, the system integrator should provide an implementation and link with it. This implementation could be from musl, from BSD or from elsewhere. It could even be an implementation with a proprietary license or with GPL, since it is not a part of civetweb (CivetWeb needs to retain a pure MIT license) - it's up to the system integrator to choose an implementation which matches his C runtime and his license requirements. 
This problem is much easier to solve for a special system, as compared to implementing a general solution for all C runtimes and the strict license requirement we have here.


With this insight, I could merge your initial pull request (adding `#if !defined(NO_TIMEGM)`).
But I do recommend you add your own `timegm` implementation and just link with it.
I think, you do not even need to change anything in the source code (civetweb.c+.h), since the linker will take care if the `timegm` function is implemented as non-static function in another `.c` file. If this works as expected, it is the most flexible solution. If it does not work out of the box, there are probably just some minor adaptations in order to get it working, and they could certainly be added with some defines in civetweb.c. I did not test it, but anyway it makes more sense if you test it for your environment.

**Comment by c-mauderer** [comment]
I've no problem with not adding a timegm(). My initial solution disabled this feature anyway.

Adding a timegm() to the application might be a solution but it would lead to the same problem that you described. It has to match the library version. Of course I could just return the maximum value for timegm and disable the caching feature with this. But this would have the character of a hack. Further it could lead to problems if another part of the software tries something similar and uses another implementation for timegm().

So from my point of view a compile time option would be a better solution.

Please note: In the mean time, i noted a bug in the patch (the is_not_modified() function should return an integer and not "false") so **I will have to rework the patch**. But It would be nice, if an updated version could be integrated.

I will update the patch shortly. It might be a better idea to rename the define to NO_CACHING to better define the result. I'll do that too.

**Comment by bel2125** [comment]
> Adding a timegm() to the application might be a solution but it would lead to the same problem that you described.

It would be easier to do it as a system specific file added to the build, because you do not need a generic, system independent solution, but you can create a system dependent table.
Anyway, let's add the `NO_CACHING` option. If you add a configuration to the `.travis.yml` file, the continuous integration (CI) test will also run automatically - I would just use the configuration with all features set, and set the NO_CACHING option. Or I can do this later, if you prefer.

**Comment by c-mauderer** [comment]
I added a patch to add it to .travis.yml. I've never worked with Travis so please correct me if I did it wrong.

**Comment by bel2125** [comment]
The CI test is running - https://travis-ci.org/civetweb/civetweb/builds/127313868
`- FEATURES=32` will probably not work. FEATURES is a bit mask calculated here: https://github.com/civetweb/civetweb/blob/master/src/civetweb.c#L13021
Since `NO_CACHING` does not have a feature bit yet, it must be 31.
But let's just wait for the CI test to finish, I can take care of it later.

**Comment by c-mauderer** [comment]
I wondered what the FEATURES would be for. It looked like a counter that is just counted up. So I just used the next value.

If you want I can change that before the merge so the merge commit is a clean one.

**Comment by bel2125** [comment]
Only the FEATURES=32 tests failed.
If you could set the FEATURES value properly, it would be a clean commit.

Probably I will add a FEATURES flag for cache later anyway, but this can be done by me later.

**Comment by c-mauderer** [comment]
I changed it to 31 like you suggested. Thank you for all your work guiding me through this.

**Comment by bel2125** [comment]
It seems there is an additional problem:
https://travis-ci.org/civetweb/civetweb/jobs/127613387

> 415Scanning dependencies of target sqlite
> 
> 416[  1%] Performing patch step for 'sqlite'
> 
> 417Error copying file "/home/travis/build/civetweb/civetweb/src/cmake/sqlite/CMakeLists.txt" to "/home/travis/third-party/src/sqlite/CMakeLists.txt".
> 
> 418make[2]: *** [/home/travis/third-party/src/sqlite-stamp/sqlite-patch] Error 1
> 

I don't see a reason why it should need sqlite ...
the real problem is here:

ENABLE_LUA=YES  
ENABLE_DUKTAPE=YES  

Lua does not build in TravisCI currently - the integration of third party components into the CMake build has not been made yet.
I will have a look to the .travis.yml in more detail.

**Comment by bel2125** [comment]
This part is ok:

  ```
583 645        - FEATURES=31  
584 646          BUILD_SHARED=NO  
585 647          NO_FILES=NO  
586 648        ENABLE_SSL=YES 
587 649        NO_CGI=NO 
588 650        ENABLE_IPV6=YES 
589 651          ENABLE_WEBSOCKETS=YES  
590 652          ENABLE_LUA=NO  
591 653          ENABLE_DUKTAPE=NO  
 654   +      NO_CACHING=NO  
592 655        - FEATURES=31  
593 656          BUILD_SHARED=YES  
594 657          NO_FILES=NO  
595 658        ENABLE_SSL=YES 
596 659        NO_CGI=NO 
597 660        ENABLE_IPV6=YES 
598 661          ENABLE_WEBSOCKETS=YES  
599 662          ENABLE_LUA=NO  
600 663          ENABLE_DUKTAPE=NO  
 664   +      NO_CACHING=NO  
```

Then it should be 

```
 665   +    - FEATURES=31  
 666   +      BUILD_SHARED=NO <-------------  
 667   +      NO_FILES=NO  
 668   +      ENABLE_SSL=YES  
 669   +      NO_CGI=NO  
 670   +      ENABLE_IPV6=YES  
 671   +      ENABLE_WEBSOCKETS=YES  
 672   +      ENABLE_LUA=NO <------------------  
 673   +      ENABLE_DUKTAPE=NO <-----------  
 674   +      NO_CACHING=YES <-------------
 675   +    - FEATURES=31  
 676   +      BUILD_SHARED=YES  
 677   +      NO_FILES=NO  
 678   +      ENABLE_SSL=YES  
 679   +      NO_CGI=NO  
 680   +      ENABLE_IPV6=YES  
 681   +      ENABLE_WEBSOCKETS=YES  
 682   +      ENABLE_LUA=NO  <--------------  
 683   +      ENABLE_DUKTAPE=NO  <---------  
 684   +      NO_CACHING=YES  
```

**Comment by c-mauderer** [comment]
I would have been surprised, if the test cases from line 645 to 664 would have been wrong. I haven't written them ;-)

For the other cases: It seems that I have misinterpreted the two test cases for every feature set. I thought that it is a base set (with a useful feature combination) and than the tested feature one time disabled and one time enabled. Now I see that you dis- / enabled the BUILD_SHARED for each feature.

I adapted the patch like you suggested and added it to my pull request. I hope that this time Travis is happy with it.

**Comment by bel2125** [comment]
Still not working: https://travis-ci.org/civetweb/civetweb/jobs/127875643

```
/home/travis/build/civetweb/civetweb/test/private.c: In function ‘test_parse_date_string’:

/home/travis/build/civetweb/civetweb/test/private.c:544:2: error: implicit declaration of function ‘parse_date_string’ [-Wimplicit-function-declaration]

/home/travis/build/civetweb/civetweb/test/private.c:560:10: error: ‘month_names’ undeclared (first use in this function)

/home/travis/build/civetweb/civetweb/test/private.c:560:10: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by c-mauderer** [comment]
Yes. Already noted it. I just tested to build with the Makefile and that worked fine. I could reproduce the bug with cmake on my local system.

It seems that there is one test that checks if the test_parse_date_string is working. I disabled this function so of course it's not. I will analyze the test and find out, if I can modify it.

**Comment by bel2125** [comment]
It needs an 
```
#if !defined(NO_CACHING)
```
from
https://github.com/civetweb/civetweb/blob/master/test/private.c#L539
to
https://github.com/civetweb/civetweb/blob/master/test/private.c#L583

**Comment by c-mauderer** [comment]
I've added the two lines. I just had to take another look because some other tests went wrong too and I wanted to avoid to annoy Travis (and probably you too) once again. But it turned out that the other test just didn't find the SSL certificates because I started the test from the wrong directory.

**Comment by c-mauderer** [comment]
Travis is happy now. But it seems that I decreased the coverage. Probably by adding some additional lines to the code? I wouldn't be sure how I should test the new lines. I more or less just added some #ifdefs.

**Comment by bel2125** [comment]
Don't worry if the test coverage decreasing by less than a percent if you add a few lines.
The pull request can be merged now.
Thank you for your contribution.

**Comment by c-mauderer** [comment]
Great. Thank you.

**Pull request merged**
