### PR TITLE
Build Conan package in CI (#712 )

### LINKED ISSUE #712: Distribute CivetWeb Conan package
Hi!

It's really nice to see Conan support in your project :1st_place_medal: 

However, the package is not being distributed on [Conan Center](https://bintray.com/conan/conan-center) server. The advantage is building your project using multiple configuration and distributing all binary package.

Including Conan CI support for your project is can be really simple and even I could help you.

Regards!

/cc @steakhal

### PR DESCRIPTION
**Pull request by uilianries**
Hi!

This PR is related to issue #712.

Here I list some important points in this PR:
- Travis CI jobs to build Civetweb as Conan package in Linux and Macos
- Appveyor jobs to build Civetweb as Conan package in Windows
- Add test package to validate the Conan package created
- Fix bad support for clang 4 (flto)
- Apply new Conan conventions from 1.8

Conan jobs will be executed **ONLY** for Github tags. Any other PR will not trigger a new job, otherwise your CI time will increase.

I've created a virtual tag in my fork to check that conditional:
https://github.com/uilianries/civetweb/tree/v1.12
https://travis-ci.com/uilianries/civetweb/jobs/167366381
https://ci.appveyor.com/project/uilianries/civetweb/builds/21266286

Conan uses the file conanfile.py as recipe to execute all steps necessary to create the package. As your project is a library, it needs to be built, and Conan defines the package id by settings + options + requires.

To make sure that your package is working well, Conan provides test_package, where we put a simple example consuming your package and building as well. When test_package.cpp is including civetweb header, all files are imported from the packaged provided by Conan. Test package is not for unit testing propose, it's a package validation.

When running your package on CI (appveyor, travis or any other) we could run Conan to create the package and check. But prepare a full environment with compiler, build-essential , conan and all stuff could be boring, so we use Docker. Conan provides a good range of images, including gcc and clang. I added multiple jobs because your project should match (compiler version, arch, os, release/debug) when required as dependency.

## How to upload?

Conan uses Bintray to store their packages. You need to create an account on bintray for that. There is a good documentation how to create a bintray account [here](https://docs.conan.io/en/latest/uploading_packages/bintray/uploading_bintray.html).

In short, you need to create a new account [here](https://bintray.com/signup/oss).
So you will have two options:

    Create a repository based on your username
    Create a new organization and so create a new repository.

I would recommend the second one, because you will be able to add more people to maintain your organization.

Following the second choice, create a new organization named civetweb or any preferred name. And create a new repository named conan or any preferred name.

The build.py is configured following the reference civetweb/conan/civetweb/. Where:

civetweb is your Bintray organization name
conan is the repository name
civetweb is the package name

Also, build.py has a rule to upload only tags or any branch with the pattern name "v(\d+.\d+)".

And finally, you must set the variable CONAN_PASSWORD on Travis settings. The password is the Bintray API Key, it's not your account password. To read your API key you need to access bintray.com/profile/edit and click on API Key button. Don't forget to mark as secret on Travis settings.
Bintray package page

After to upload your package by CI, we recommend update your Bintray package page:
bintray.com/civetweb/conan/civetweb%3Acivetweb/edit?tab=general
The page contains only project metadata, as url, maturity (official), license.
Conan Center request

Now that all steps are done. Just click on "Add to Conan Center" button, present on your package page, and wait for a review.

Okay, this is a lot of information. Please, feel free to ask anything.

I'm including @danimtb and @SSE4 to review this PR. They are Conan experts.

Regards!

/cc @danimtb @SSE4

closes #712

### CODE REVIEW

**Comment by uilianries** [comment]
Thanks!

**Comment by bel2125** [comment]
Thanks for your contribution.

I created the bintray account with the names you proposed - so there is a page https://bintray.com/civetweb/conan/civetweb/ now.

I think I also set the CONAN_PASSWORD variable to the API key.
Thanks for your detailed explanation how to do this.


Next step is
> After to upload your package by CI ...

Isn't this done automatically?
Or do I need to so something manually?

**Comment by bel2125** [comment]
It seems bintray is not a free service:

> Hello bel2125,
>
> Your Bintray trial will end in 7 days!
>
> To continue using Bintray and keep your premium repositories, please purchase a subscription.
Once your trial period ends, without a premium subscription, all of your premium content will be permanently deleted.
>
> For any question, contact us at service@jfrog.com.
>
> Looking forward to hear from you,
>
> JFrog Bintray Team

**Comment by danimtb** [comment]
@bel2125 Did you sign up as an opensource account organization? Seems that you signed up with a trial premium account. This is the link to create an OSS one: https://bintray.com/signup/oss

If you sign up for a trial is to have the PRO features which are not needed in this case. I would say you have to create the organization as an OSS account in Bintray. I am going to ask the Bintray team if they can switch to the OSS version.

Thanks

**Comment by danimtb** [comment]
HI again @bel2125. Looking at you Bintray  organization, there are still no Conan packages uploaded there. Best approach would be to change you account manually (delete trial and create an OSS account). This is the less painfull way Bintray team is proposing to not interfere with the account settings.

**Comment by bel2125** [comment]
I'm not precisely sure what I did, since the bintray service is completely unknown to me.
I think I created an organisation "civetweb" and a user "bel2125" - at least this is what I intended to do, to mirror the structure on GitHub. I can't sign up a new user "civetweb" or "bel2125" using the https://bintray.com/signup/oss link , since these users already exist (yes they do - I created them). 
Should I delete the organization or the user?

**Comment by bel2125** [comment]
Deleting civetweb:
Error: "Cannot delete a premium organization account"

Deleting bel2125:
Error: "Cannot delete a user owning active organizations"

So that's not going to work.

**Comment by danimtb** [comment]
Here you have the steps to cancel the trial:

1. Click on Premium Dashboard
image
2. Click on Account:
image
3. Click on Cancel Enterprise (Trail) button:
image
4. Approve:
image

**Comment by bel2125** [comment]
tried it, got lost somewhere between account settings and organization
settings, .. but the page above now says
"Your current plan is OSS", not "Your current plan is enterprise (trial)"

But, I can not access the organization now, and I can also not import it
from github.

Organizations Identifier is already used. Please try another one.

I guess that won't work out without support from bintray

**Comment by memsharded** [comment]
Hi @bel2125 

The organization has been unblocked, could you please try again? Thanks!

**Comment by bel2125** [comment]
Now it seems to work, thanks.

I created https://bintray.com/civetweb/civetweb and was able to upload "something" (Version 1.11 ... but there was no conan build script when 1.11 was released, so I'm not sure what it did). Anyway, probably we can try to upload the current working version, or some intermediate label for test purposes?

**Comment by uilianries** [comment]
Hi @bel2125 !

Since you created a repo with the name **civetweb**, I'll need to change the `build.py` because [here](https://github.com/civetweb/civetweb/blob/master/conan/build.py#L42) I expected to use a repo with the name "conan". There is no problem using civetweb, just to be clear.

Also, the script build.py will ONLY upload a package when your current branch is a tag. We could change it to upload all packages when a new change is made on master branch, but this will increase your CI time and I think few users will be interested in download a testing package.

**Comment by bel2125** [comment]
> Since you created a repo with the name **civetweb**, I'll need to change the `build.py` because [here](https://github.com/civetweb/civetweb/blob/master/conan/build.py#L42) I expected to use a repo with the name "conan".

That was not intentional - I changed the repository name: https://bintray.com/civetweb/conan

Once everything is set up correctly, I could create a test tag. Will a "git tag" with arbitrary name ("conan_test_tag") do, or does it have to be 1.12 or a full Github release?

**Comment by uilianries** [comment]
Actually it uses a regex, not the git tag...

So you are able to pretend a tag branch just using the same pattern for your branch name. It must follow your project version pattern e.g. v1.2

The PR #735 to check if it's a real tag, but I think the current pattern is enough.

**Comment by stgatilov** [comment]
I'm sorry for stupid question, but can how can I use this civetweb package with conan?

I tried searching for "civetweb" in various remotes, but cannot find any packages. Is it available in conan-center or bincrafters? Do I need to add some specific remote to use this package?

**Comment by uilianries** [comment]
As Conan now offers the [conan-center-index](https://github.com/conan-io/conan-center-index), we can move this recipe/package there.

**Comment by bel2125** [comment]
Anything I need to do here?

**Comment by bel2125** [comment]
It seems everything in the release V1.13 worked, except the Conan scripts: https://travis-ci.org/github/civetweb/civetweb/builds/731726649
Since I do not really understand what they are doing, I cannot fix them.

**Comment by memsharded** [comment]
Hi @bel2125 

The process to publish packages in ConanCenter is to submit a PR to https://github.com/conan-io/conan-center-index. Detailed instructions are in https://github.com/conan-io/conan-center-index/blob/master/docs/README.md. 

It is still EAP so you need to apply for it sending a comment in https://github.com/conan-io/conan-center-index/issues/4.

**Comment by bel2125** [comment]
> It is still EAP so you need to apply for it sending a comment in conan-io/conan-center-index#4.

Done and accepted by the ConanCenter.

I checked these instructions: https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md and compared to the files in this pull request. We already have a conanfile.py there. However, there is no TravisCI related information in this link above, and the pull request is definitely Travis related.
Currently I still don't feel able to fix this issue by myself, since I'm still missing how all these pieces are supposed to work together. What is already done in this PR, what changed on Conan and/or Travis since that time - and what needs to be done now?

**Pull request merged**
