### PR TITLE
On i386 (non-i686) builds __sync_(add|sub)_and_fetch is not available.

### PR DESCRIPTION
**Pull request by tzimmofsecure**

### CODE REVIEW

**Comment by bel2125** [comment]
I'm not sure if this is the right way to do this.

First of all, `__i686` does not appear in [this list](https://sourceforge.net/p/predef/wiki/Architectures/) or [this list](http://nadeausoftware.com/articles/2012/02/c_c_tip_how_detect_processor_type_using_compiler_predefined_macros) and I don't get it with `gcc -dM -E - < /dev/null` either (I also don't get `__i386` but `__x86_64__`).

Also, the [GCC documentation](https://gcc.gnu.org/onlinedocs/gcc-4.4.5/gcc/Atomic-Builtins.html) does not mention any platform specific requirement. 

As to my knowledge, __sync_add_and_fetch compiles to LOCK XADD and should be available at least for [i486](https://en.wikipedia.org/wiki/X86_instruction_listings#Added_with_80486) (introduced in 1989). So all x86 CPUs from the last 25 year should support it.

Could you provide some reference for this define?

**Comment by bel2125** [comment]
> So all x86 CPUs from the last 25 year should support it.

I just found 80386 were produced until 2007 (according to [Wikipedia](https://en.wikipedia.org/wiki/Intel_80386) from October 1985 to September 2007). Still, is supporting 80386 the intention?

**Comment by tzimmofsecure** [comment]
We have customers and some may be running really old hardware and we have no control over it. Thus compiling for i386 (for 32-bit builds) is what we have been doing so far.

On a 32-bit system: (CentOS 5.11 32-bit in this case)

--8<--8<--
$ echo | gcc -dM -E - | grep i.86
#define __i386 1
#define i386 1
#define __i386__ 1
$ echo | gcc -march=i686 -dM -E - | grep i.86
#define __i686 1
#define __i686__ 1
#define __i386 1
#define i386 1
#define __i386__ 1
--8<--8<--

but actually -march=i486 and -march=i586 would be possible as well and then that __sync_add_and_fetch() is probably present as well.

And the original issue was:

--8<--8<--
$ gcc  -Wall -W -Wno-traditional -Wundef -Wshadow -Werror  -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wnested-externs -Winline -fPIC -DNO_SSL -Wno-unknown-pragmas  -I . -I include             -g -c -o civetweb.o src/civetweb.c
$ gcc  -Wall -W -Wno-traditional -Wundef -Wshadow -Werror  -Wpointer-arith -Wbad-function-cast -Wwrite-strings -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wnested-externs -Winline -fPIC -DNO_SSL -Wno-unknown-pragmas  -I . -I include             -g -c -o main.o src/main.c
$ gcc -o civetweb main.o civetweb.o -pthread -lrt
civetweb.o: In function `mg_atomic_inc':
/home/tzimmo/git/civetweb-build-clean/civetweb-build/build/civetweb/src/civetweb.c:815: undefined reference to `__sync_add_and_fetch_4'
civetweb.o: In function `mg_atomic_dec':
/home/tzimmo/git/civetweb-build-clean/civetweb-build/build/civetweb/src/civetweb.c:834: undefined reference to `__sync_sub_and_fetch_4'
collect2: ld returned 1 exit status
--8<--8<--

I'm open to other alternatives in resolving this as well if you have any ideas in mind?

**Comment by bel2125** [comment]
The fallback
```C
ret = (++(*addr));
```
isn't really atomic. When I wrote it, I thought no platform will ever use this. I also thought about just writing 
```C
#error "You use a platform unknown to me. Please implement atomic-inc on your own."
```
So I wonder this piece of code is really in use.

Regarding your pull request: 
First of all, I'm afraid it might lead to some platforms using this fallback code, although it would not be required for this platform. An explicit define `NO_SYNC_AND_FETCH` (in analogy to `NO_POPEN`) would be a way to avoid using compiler specific system defines in a wrong way, and accidentally using the fallback. If you know exactly what you are doing, you could add this define to your build. I think 486 already has the required operations, but I don't know if the compiler supports it (old versions of Visual Studio had to use [emit](https://msdn.microsoft.com/en-us/library/1b80826t.aspx) for this, don't know for old gcc versions).
Next, `ret = (++(*addr));` could cause problems anyway - you probably add a `pthread_mutex_lock`/`.._unlock` pair, using a mutex global to your entire application - not to the civetweb context, since you need to create it before the first call to `mg_start`, and never destroy it (until the application exits). In the recent version, it could be done in `mg_init_library`, but then using this init function is mandatory.
You could also write your own __sync_add_and_fetch function, and link it in case there is no built-in. 

Maybe you do not have this issue, if your minimum platform is an 80486?

By the way - I don't get a list of defines for 486:
```
> echo | gcc -march=i486 -dM -E -
cc1: error: CPU you selected does not support x86-64 instruction set
cc1: error: CPU you selected does not support x86-64 instruction set

> gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

**Comment by tzimmofsecure** [comment]
You don't get a list because you are using 64-bit compiler targeted to create 64-bit (x86_64) binaries, thus you cannot compile for i486 architecture (there is no i486 for 64-bit). But if you add -m32 to the gcc command line, it instructs it to target for 32-bit architecture, such as i486, for example, so:

echo | gcc -m32 -march=i486 -dM -E -

probably works for you. Not sure if it needs some 32-bit development packages though, maybe not.

And yes, a separate -D(efine) could be used instead. Another thing is that if this atomic operation is not done too often to cause too much performance penalties (I didn't check how often it gets called), using a mutex around it could be an option on all platforms as well. Civetweb is threaded anyway, so having a mutex might not be too bad option.

As I cannot tell what the customers are running, I cannot say for sure that i486 is not too modern for some of them.

**Comment by bel2125** [comment]
Although I can't guarantee anything, I think it's actually not really dramatic, if "atomic" operations are not atomic on single core CPUs with the current default feature defines, if you don't call mg_start twice the same time from different threads and don't use the alternative queue define. Some statistics data might be wrong (number of active clients, used memory, ...) but that's not used for anything but showing statistics. Still there should be this lock if there is no sync operation - making the init library call mandatory for those platforms.

**Comment by bel2125** [comment]
`echo | gcc -m32 -march=i486 -dM -E -`  works, thanks.

**Comment by bel2125** [comment]
> Another thing is that if this atomic operation is not done too often to cause too much performance penalties (I didn't check how often it gets called), using a mutex around it could be an option on all platforms as well. Civetweb is threaded anyway, so having a mutex might not be too bad option.

if `USE_SERVER_STATS` is set, `mg_atomic_inc` and `mg_atomic_add` are called quite often.

The original intention of `mg_atomic_inc` was, to check if `mg_start` is called the first time, and some one time initialization needs to be done. Retrospectively, the simpler way would have been to add an init library function earlier, and require it to be used before mg_start (maybe with some compatibility fallback to call mg_init_library from there, but leaving a memory leak).

Then it got used to create thread indexes - that's a rare operation and a lock would be possible there.

It's used to refresh trusts - don't know if you use short time certificates.

And there is server statistics.

**Comment by bel2125** [comment]
I added the 'NO_ATOMICS' define some days ago.
Maybe this will solve your problem.

**Comment by bel2125** [comment]
a `#define NO_ATOMICS` should solve your problems, and it's even multi-threaded safe now:

```C
	mg_global_lock();
	ret = (++(*addr));
	mg_global_unlock();
```

**Comment by bel2125** [comment]
The `NO_ATOMICS` define will solve this problem.
In case there are still unresolved issues, please open a new issue.

**Pull request closed without merging**
