### PR TITLE
Add config option for enabling the TCP_NODELAY option on client sockets

### PR DESCRIPTION
**Pull request by waltsteverson**
The default 40ms TCP socket send delay between REST API responses was the cause of dramatically slower queries-per-second when HTTP 1.1 keep-alive is enabled.  Enabling the TCP_NODELAY socket option on client sockets improved performance by orders of magnitude (~25 requests per second --> ~10000 requests per second).

### CODE REVIEW

**Comment by bel2125** [comment]
This can be merged without the white-space policy changes.
Thank you.

**Comment by bel2125** [comment]
Since it introduces a new option, this must be documented here:
https://github.com/civetweb/civetweb/blob/master/docs/UserManual.md

Any suggestions for a documentation text?
Will you write it or should I do it?

**Comment by waltsteverson** [comment]
How about this for documentation text?

-----------------------------------------------------

### tcp_nodelay no

Enable TCP_NODELAY socket option on client connections, either yes or no.

If set the socket option will disable Nagle's algorithm on the connection which means that packets will be sent as soon as possible instead of waiting for a full buffer or timeout to occur.

**Comment by bel2125** [comment]
That's fine for a first version - one can still improve it later on.
Will you add it or should I do?

**Comment by waltsteverson** [comment]
Due to my inexperience with git/github, I'll let you do it if you don't mind.

**Comment by bel2125** [comment]
Ok, I will merge the code and add the documentation afterwards.
Thank you for your contribution.

**Comment by bel2125** [comment]
I plan to change the `tcp_nodelay` option to have three states instead of two (`yes` and `no`).
The states would be
* off for everyone - the way it worked in V1.7 and before, currently the default setting `no` 
* on for everyone - the current `yes`
* on only for websockets, off for everyone else 

It is not possible to configure this as a boolean option with only `yes` or  `no`, so I have to change the option type before the next release. Once it is released, I want to avoid such incompatibilities, so I want to change the option type earlier.

**Pull request merged**
