### PR TITLE
Added background script parameters and shutdown detection

### PR DESCRIPTION
**Pull request by BigJoe01**

### CODE REVIEW

**Comment by bel2125** [comment]
Please, everybody, provide at least one or two lines of description for your pull requests.
https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md
Yes, I can read it from the code in a minute or two - but others maybe not.

Anyway: 
Thank you for contribution. I will merge it.
Will you provide a brief description for `lua_background_script_params`, to add it to doc/UserManual.md?

**Comment by bel2125** [comment]
Merged.
Thanks for your contribution.

**Comment by BigJoe01** [comment]
Next week i want update User manual, and next time i adding more information to commit.
Sorry for inconvenience.

**Comment by bel2125** [comment]
Don't worry, a working contribution is never an inconvenience.
Still, an example for the documentation would be welcome.
Do you have an example how to use the "shutdown" variable in Lua?

**Pull request merged**
