### PR TITLE
Add conan packaging file

### PR DESCRIPTION
**Pull request by deblauwetom**
A conan packaging file. I'm not very proficient in conan, but it could be a starting point for more!

### CODE REVIEW

**Comment by bel2125** [comment]
Thanks for your contribution.
Merged.

Since I personally do not use conan and have no experience with it, I can not promise to maintain this file in a way future changes will work out of the box. But it could certainly be more helpful than "no conan file" ;-)

**Comment by deblauwetom** [comment]
ok, thanks!

Just mention that you can test the package here:

`conan remote add metalmajor https://api.bintray.com/conan/metalmajor/metalmajor`

and you can add this to your conaninfo.txt in the "requires" section:

cpr/1.3.0@metalmajor/testing

**Comment by bel2125** [comment]
Sorry, I don't have "conan" installed - if I type it to my Linux shell, it asks me if I want to install "»conman« (universe)" - and I don't know a conaninfo.txt file. 
I'm probably too far to understand your short descriptions and would need a link to basic introduction.

But let me ask it this way: Is there a simple way to add it to the existing Travis CI and/or AppVeyor unit tests, so I can see if something is broken?

**Comment by deblauwetom** [comment]
yes, well, you can just "use" my repo and then conan will download and compile from my package that I uploaded to my own conan remote.

So to test my package first install conan from "conan.io", and add my remote:

```
conan remote add metalmajor https://api.bintray.com/conan/metalmajor/metalmajor
```
Then, you can create a text file called "conanfile.txt" and put this in it:
```
[requires]
	civetweb/1.10@metalmajor/testing

[generators]
    cmake
```
Now this command should fetch and build the package, and create a cmake file which you can then use in a cmake project:
```
conan install conanfile.txt
```

If you want to build the package from the civetweb source directory, then you could do this:
```
cd civetweb
conan create . civetweb/1.10.0@bel2125/testing
```
And that will build and create the package locally. Then you can change the line in the conanfile.txt to require your package for example. It is then possible to upload the package to some remote with 
```
conan upload civetweb/1.10.0@bel2125/testing -r <your-remote>
```
Hope this helps!

**Pull request merged**
