### PR TITLE
print query sting in url

### PR DESCRIPTION
**Pull request by sunfch**
print query string after character of "?" in url

### CODE REVIEW

**Comment by bel2125** [comment]
Something seems not correct with this code:

Both, GCC and clang report a lot of errors in the [log_access function](https://github.com/sunfch/civetweb/blob/patch-1/src/civetweb.c#L9774):
GCC: https://travis-ci.org/civetweb/civetweb/jobs/93781848
clang: https://travis-ci.org/civetweb/civetweb/jobs/93781985

**Comment by bel2125** [comment]
`ri->query_string ? ri->query_string ? "",`
is probably supposed to be
`ri->query_string ? ri->query_string : "",`
 
`? :` instead of `? ?`

Can you correct your merge request?

**Comment by sunfch** [comment]
It's my mistake!  I have correct it. 
Thanks

**Comment by bel2125** [comment]
merged. Thank you.

**Pull request merged**
