### PR TITLE
Fix ret cast type on evhdl to work on older compilers.

### PR DESCRIPTION
**Pull request by colmartofus**

### CODE REVIEW

**Comment by bel2125** [comment]
d3bf8b12122af3fd03e1358e49fa2f5875bf29eb is certainly correct. 

But 770a3b3a2da89eed457edeab904a349bbee877e6, replacing `(int)eventhdl` by `*(int *)eventhdl`, will not have the expected effect.

```
create_event does
int evhdl1 = eventfd(0, EFD_CLOEXEC);
ret = (int *)evhdl1;
return (void *) ret

event_wait(void *evhdl1) does
**evhdl2 = *(int *)evhdl1;**
read(evhdl2, ...)
```

this will effectively interpret evhdl1 as a pointer, and even if this does not yield in an access violation, evhdl2 will be different.

It will only work if you drop
```
 	if (sizeof(int) == sizeof(void *)) {
		ret = (int *)evhdl;
 	} else {
```

completely, and only work with the `else` branch

```
 		ret = (int *)mg_malloc(sizeof(int));
 		if (ret) {
 			*ret = evhdl;
 		} else {
 			(void)close(evhdl);
}
```

**Comment by colmartofus** [comment]
You're right. I'll try to clean this up.

**Comment by bel2125** [comment]
Maybe the entire `if (sizeof(int) == sizeof(void *))` special case is not really required.
It only saves one "malloc" when creating the event.

**Comment by bel2125** [comment]
cherry picked d3bf8b12122af3fd03e1358e49fa2f5875bf29eb

**Pull request closed without merging**
