### PR TITLE
Add parameters for thread stack size, priority and policy.

### PR DESCRIPTION
**Pull request by c-mauderer**
This adds the following three parameters:
   * --thread_stack_size: Set the stack size of the threads.
   * --thread_priority: Set the priority of the thread.
   * --thread_policy: Set the scheduling policy of the thread.

The additional parameters simplify the integration of civetweb as a library
with changing requirements regarding to thread creation.

### CODE REVIEW

**Comment by c-mauderer** [comment]
Seems that I have to rework the patch. See https://groups.google.com/forum/#!topic/civetweb/_Mul9PxgpBE

**Comment by bel2125** [comment]
Let's discuss the entire problem, and what would be the best solution in the google group:
https://groups.google.com/forum/#!topic/civetweb/_Mul9PxgpBE

**Comment by bel2125** [comment]
Are there any news on this topic?

**Comment by c-mauderer** [comment]
Hello bel,

only that I currently don't find the time to properly create the patch like we discussed in the forum. Therefore I think it would be best to close the request for now. I hope that I can reopen it sometimes in the future when I have the time to implement it.

I'm really sorry that I used so much of your time. Thank you for all your help in this matter.

**Comment by bel2125** [comment]
You are welcome.
Just open the issue again when you have time to deal with this topic.

**Pull request closed without merging**
