### PR TITLE
Added optional additional_headers for mg_send_mime_file

### PR DESCRIPTION
**Pull request by PhilLab**
This allows to put additional file meta data in your header fields

### CODE REVIEW

**Comment by bel2125** [comment]
One of the TravisCI tests failed - maybe just some problem of the build server (this happens from time to time), so I restarted the test.

However, this is also an interface change and might lead to compatibility issues.
I'll be on vacation for 10 days now, we can discuss more details afterwards.

**Comment by PhilLab** [comment]
okay, thanks. Have a great vacation!

**Comment by bel2125** [comment]
Thanks.
Maybe a solution for the incompatibility could be to use the MG_LEGACY_INTERFACE define, as already used at several other places. Maybe it is time to do some more API cleanup, and document what needs to be changed ... let's discuss this later.

**Comment by bel2125** [comment]
I spent some time thinking on this proposal, and found a second compatibility problem
- the first one was a backward compatibility issue (changing the existing mg_send_mime_file interface)
- the second one is a "forward" compatibility issue:
If you manually set an additional HTTP header in your code, and I (or someone) later decides to add the very same HTTP header with some default value (or a configured one) to civetweb.c, the server will send the same header twice, probably with different values, violating the HTTP protocol. But we need to be able to add a new HTTP header to the default in civetweb.c if this is meaningful/required. The problem is basically a shared responsibility for sending consistent HTTP headers. We could specify _"in order to know what headers you are allowed to send, you have to read the civetweb source"_ (because a second documentation needs to be maintained or is not up do date) and _"this may change from version to version without further notice"_ (because we need some liberty of action as discussed above), but these restrictions are not really satisfying for an external interface.

Could you give some examples of the headers you want to send.

**Comment by PhilLab** [comment]
> Could you give some examples of the headers you want to send.

Sure: In my application I have to deliver Android install packages (.apk). In order for my client to detect if an upgrade is necessary, I send the version code in the headers, using the ``X-`` prefix for the header field:
``header = "X-APK-VersionCode: " + std::to_string(versionNumber);``

**Comment by bel2125** [comment]
> Do you fear that the list would become outdated?
This is one problem: I (or someone) adds a new header and forgets to add it to the documentation.
Even if I add a comment "add this to the documentation", this comment could be in the wrong place, if a function calls a function calls a function ... sending one header.

The other issue is, I documented to use 5 headers, you send a sixth in your private code.
The next version I come to the conclusion it makes sense to send the same header as you already did, and I add it. The new version will be incompatible for you, and you won't get any compiler/linker/... warning.

But I understand the need for additional headers now, and I understand they can not be added using a static configuration. Probably adding the interface with some sneaky warning "make sure you don't send the same header as civetweb.c" and "note, the headers sent by civetweb may change from version to version" is still the best solution.  I am 99.999999999% sure, civetweb will never send a X-APK-VersionCode header in the default.

**Comment by PhilLab** [comment]
One idea which just came to my mind: Although the ``X-`` prefix is [deprecated](https://tools.ietf.org/html/rfc6648) we could use exactly this fact, i.e. guarantee in the method-documentation (and probably also an inline comment) that this function does not add ``X-something`` headers and provided additional headers MUST start with "X-".
The latter could be a) left entirely in the user's responsibility b) checked before sending or c) enforced by automatically adding an X- to each line's beginning. I think I prefer option a) here.

**Comment by bel2125** [comment]
I would definitely exclude c) 

For headers with X- a) and b) are equivalent.
The behavior for headers without X- is unspecified, so a) and b) are both valid, even switching between them without further notice would be valid. So let's use a)

**Comment by PhilLab** [comment]
Added documentation. Do you think it is sufficient? Should we add a test making sure the function does not include X- headers when additonal_headers==NULL and if so - how?

**Comment by bel2125** [comment]
>Added documentation. Do you think it is sufficient? 

You mean "Each header must start with an X- to ensure it is not included twice." from the header?
I dont think it's sufficient for users, but I'm going to append more text later. So it's sufficient for the pull request :-)

> Should we add a test making sure the function does not include X- headers when additonal_headers==NULL ...?

No. 
I can not imagine  good reason to add X- headers - but if there would ever be a strong reason, we would have to do it anyway and remove the test again. So I would not create a test like this.


So the backward compatibility issue (changing the existing mg_send_mime_file interface) still remains. 
We need a new function ´mg_send_mime_file2´ t avoid this.

**Comment by bel2125** [comment]
Are you going to change the ´mg_send_mime_file´ to ´mg_send_mime_file2´, so I can merge the PR?
Or should I change it? 

The Travis CI tests do have some errors, but this seems to be an error in Travis (https://github.com/civetweb/civetweb/issues/345), not in your code.

**Comment by bel2125** [comment]
I needed to restart build 730.162 (https://travis-ci.org/civetweb/civetweb/jobs/156138034) again, due to the annoying instability of Travis CI (#345). I think it's time to merge this now.
Thanks for your contribution.

**Pull request merged**
