### PR TITLE
CMakeLists: Use GNUInstallDirs to determine install directories

### PR DESCRIPTION
**Pull request by mikecrowe**
CMake's GNUInstallDirs knows where particular Linux architectures and
distributions want to have their libraries installed. In particular,
Debian-derived "multi-arch" distributions keep their libraries in triplet
directories under /lib. Other "bi-arch" distributions keep 64-bit libraries
in /lib64.

Including GNUInstallDirs and using CMAKE_INSTALL_LIBDIR,
CMAKE_INSTALL_BINDIR and CMAKE_INSTALL_INCLUDEDIR means that civetweb's
libraries, binaries and header files are installed in the correct
collection.

The placement of the include(GnuInstallDirs) appears to be critical to
ensure that the variables it uses are available. Immediately after
determine_target_architecture appears to work for me.

Tested with OpenEmbedded and on Debian GNU/Linux 9 (the special naming only
applies when installing in /usr.)

### CODE REVIEW

**Comment by mikecrowe** [comment]
It doesn't look like the build failure is related to the change I made, and another pull request failed with the same thing. :(

**Comment by bel2125** [comment]
I fixed the error and restarted the CI test.

**Comment by bel2125** [comment]
Works after fixing the unrelated error.

**Comment by bel2125** [comment]
Thanks for your contribution.
Merged.

**Pull request merged**
