### PR TITLE
Fix some compiler warnings. Fix some issues reported by Coverity.

### PR DESCRIPTION
**Pull request by tzimmofsecure**

### CODE REVIEW

**Comment by tzimmofsecure** [comment]
There seem to be bunch of failures but at least the ones I checked at random were related to variable 'date' not being available because the declaration was inside #if !defined(NO_FILES) but the code using it is not.

**Comment by bel2125** [comment]
Static source code analysis is something mysterious. I'm already used to two different analysis tools showing completely different warnings, but in this case it seems Coverity reports different warnings to you and to me???
Civetweb builds without warnings on gcc, clang and MSVC with -wall, -wextra, ... all clang scan-build warnings are false positives and the [online version of Coverity](https://scan.coverity.com/projects/5784) just returns [two minor warnings](https://scan.coverity.com/projects/bel2125-civetweb/view_defects). Coverity did not show me the errors you mentioned above.

However, your fixes seem reasonable - thanks, I will merge it.
But it seems I need to do this manually due to some merge conflicts.

**Comment by tzimmofsecure** [comment]
The conflict is easy to resolve. The latest fix for date generated the conflict. It was clean at the point of making the pull request.
I'm using quite strict settings both of Coverity and in gcc. While -Wall -W -Wextra enables most warnings, they don't enable all of them. And we are building this on multiple platforms, multiple distributions and multiple versions, some of which are pretty old, like RHEL 5, in order to build binaries that work for all our customers. Different compiler versions and architectures warn about different things.
We use different options for different compiler versions, but among those options are, in addition to those -Wall -W -Wextra:
-Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wwrite-strings -Wconversion -Wsign-compare -Waggregate-return -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wredundant-decls -Wnested-externs -Winline -Wlong-long -Wcast-align -ansi
Some of them are enabled on some compiler versions without explicitly specifying them but not all of them.
And for Coverity:
--aggressiveness-level high --all --enable-callgraph-metrics --enable-fnptr --enable-parse-warnings --hfa --security --enable-constraint-fpp

**Comment by tzimmofsecure** [comment]
And there are some more issues reported by Coverity but they were more difficult to investigate and fix and/or there are multiple alternatives how to fix them. And there are maybe some false positives that cannot happen in reality but the code fools Coverity. And in a library's case Coverity cannot know how the caller will eventually call the functions as it cannot see the calling code (which might not even exist yet at the time of analysis because it hasn't been even written yet).

**Comment by tzimmofsecure** [comment]
Oh, one more thing: The code supports many different combinations of enabling/disabling features, and Coverity should actually be run with all the combinations to catch all the issues. Maybe we are using a different combination of features than you are and thus we are seeing different issues.

**Comment by bel2125** [comment]
This is the way I do the coverity scan:
https://github.com/civetweb/civetweb/blob/master/resources/coverity_check.sh
```
cov-analysis-linux64-8.7.0/bin/cov-build --dir cov-int make WITH_IPV6=1 WITH_WEBSOCKET=1 WITH_SERVER_STATS=1
```

And here is the list of compile flags:
https://github.com/civetweb/civetweb/blob/master/CMakeLists.txt#L259
```
add_c_compiler_flag(-Wall)
add_c_compiler_flag(-Wextra)
add_c_compiler_flag(-Wshadow)
add_c_compiler_flag(-Wconversion)
add_c_compiler_flag(-Wmissing-prototypes)
add_c_compiler_flag(-Weverything)
add_c_compiler_flag(/W4)
add_c_compiler_flag(-Wno-padded)
add_c_compiler_flag(/Wd4820)
add_c_compiler_flag(-Wno-unused-macros)
add_c_compiler_flag(-Wno-format-nonliteral)
add_c_compiler_flag(-Wparentheses)
if (MINGW)
  add_c_compiler_flag(-Wno-format)
endif()
if (NOT CIVETWEB_ALLOW_WARNINGS)
  add_c_compiler_flag(-Werror)
endif()
add_c_compiler_flag(/WX)
add_c_compiler_flag(-pedantic-errors)
add_c_compiler_flag(-fvisibility=hidden)
add_c_compiler_flag(-fstack-protector-strong RELEASE)
add_c_compiler_flag(-flto RELEASE)
add_c_compiler_flag(-fsanitize=undefined DEBUG)
add_c_compiler_flag(-fsanitize=address DEBUG)
if (HAVE_C_FLAG_FSANITIZE_ADDRESS)
  add_c_compiler_flag(-static-asan DEBUG)
endif()
add_c_compiler_flag(-fstack-protector-all DEBUG)
if (MINGW)
  add_c_compiler_flag(-mwindows)
endif()
```

Probably some are still missing. Any suggestions what flags should be added as a next step?

**Comment by bel2125** [comment]
The merge is indeed trivial. I just wait for the automatic test to complete.

**Comment by tzimmofsecure** [comment]
No, I'm not any expert on those flags. I have just found a working set that works across the compiler versions and platforms we are using. You seem to have a good set of flags that work on modern compilers. Older ones that we use don't support many of those.

**Comment by bel2125** [comment]
The clang warning "-Weverything" should enable every current and future warning, only three warnins are explicitly deactivated ("Wno-unused-macros", "Wno-padded" and "Wno-format-nonliteral" will remain deactivated).

I did not find out how to add flags to the Coverity scan script (cov-analysis-linux64-8.7.0/bin/cov-build). Still, while I can do [148 build configurations for every commit](https://travis-ci.org/civetweb/civetweb/builds/243653809), I cannot do more than 2 (or 3?) Coverity builds each day. So, I cannot build every combination with coverity, so I'm just using one configuration with all CivetWeb features except those using third party code.

The current warning and scan settings already seem quite strict. Still, if anyone has a suggestion for more flags (in particular for Coverity), I will add them.

Meanwhile the code is merged, thanks for your contribution.

**Pull request merged**
