### PR TITLE
Fix mg_fopen, lp scripts execution, remove executable flag from source file

### PR DESCRIPTION
**Pull request by danielrempel**
I'm not sure that this fix is sufficient for all the tasks (I expect cache can be still broken if it uses this method), but at least now I can execute lp scripts.

Guys how did this happen that you didn't even know that some of examples didn't work?

Also, I've removed executable flag from `src/civetweb.c`. It's mandatory, imo.

### CODE REVIEW

**Comment by bel2125** [comment]
The reason why `*.lp` does not work might be a 
1) The build system port to CMake (#94) does not work for Lua yet, so the automatic build tests can not test Lua
and 2) I do not use `*.lp` on my own, since there are `*.lua` pages with more features (using `*.lp` or `*.lua` is probably also a matter of taste).
and 3) there was no release in the last months, where I do manual tests of all features.

I will have a look at the problem, I think it needs to be fixed in a different way.

**Comment by danielrempel** [comment]
@bel2125, `lp` pages didn't work because of broken  mg_fopen, which didn't set file->size, which caused mmap in lp handler to fail with EINVAL.

**Comment by bel2125** [comment]
I know - and there is no doubt your patch will fix the problem.

I just thing mg_fopen should not set file->size - this should be done by mg_stat. 
The line `if (!mg_stat(conn, path, filep) || !mg_fopen(conn, path, "r", filep)) {` ([here](https://github.com/civetweb/civetweb/blob/master/src/mod_lua.inl#L1407)) seems redundant if mg_stat and fopen both set the file size. Anyway it is a maintenance problem, if functions do something else than their name suggests. 

That's why I want to fix it in a different way.

**Comment by danielrempel** [comment]
@bel2125, I think some documentation tools may help solving that. Or at least some commenting, because the code is hardly readable and some function names like mg_fopen, mg_stat etc are very misleading.

**Comment by danielrempel** [comment]
@bel2125, I expect that I'll use the project for some of my needs, including work, so I could try writing some drafts of internals documentation.

**Comment by bel2125** [comment]
Documentation is certainly welcome.
As you probably know, I took the existing project [about 2 years ago](https://groups.google.com/forum/#!topic/civetweb/gAiHqB5bLqU), and civetweb itself was forked [in mid 203](https://groups.google.com/forum/#!topic/civetweb/rcQj7MhpvHY), and there is a lot of code from 2004 to 2013, and some functions are not easy to understand.

**Comment by danielrempel** [comment]
@bel2125, OK, I'll try. Doxygen's OK?

**Comment by bel2125** [comment]
Doxygen with [GENERATE_HTML](https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_generate_html) set?
The premium solution would be to have two output files, one for the interface (civetweb.h) and another one for the implementation.

**Comment by danielrempel** [comment]
Uhmm. I don't know. The idea was to start writing doxygen compatible
comments and to decide afterwards:)
If you have any preferences - they're welcome.
You've meant two separate documentation sets for internals and for
embedding APIs?

**Comment by bel2125** [comment]
For the comments it does not matter if doxygen generated HTML, PDF, LATEX, whatever.
It only matters for me when I want to add the generated files to some release.
But you are right, this does not need to be decided now.

Yes, I mean two different documentation files for the internal functions and for the embedding API.

**Comment by bel2125** [comment]
The current fix will solve the problem.

Still a larger fix to make operations like mg_fopen and mg_stat do exactly and exclusively what their names suggest should be done. Functions should not set different members of a common output
structure (like struct file in mg_fopen and mg_stat).
However, this is more work and I need to do this when I have more time.

**Comment by bel2125** [comment]
The fix in the pull request will also solve #244 (https://github.com/civetweb/civetweb/issues/244#issuecomment-171768873).
The only reason I did not merge it yet: I thought I would find the time to rewrite mg_fopen and mg_stat to remove the stamp coupling (their use of different members in the mg_file data structure).
I decided to rewrite (or actually replace) `mg_upload` first. 
So now I think it is a good idea to merge this first, and rewrite `mg_fopen` later.

**Comment by bel2125** [comment]
Thanks for the fix.
I created a new issue for the refactoring of mg_fopen and mg_stat (#246).

**Pull request merged**
