### PR TITLE
Fix OS X link error due to missing libcompat

### PR DESCRIPTION
**Pull request by kainjow**
See https://github.com/civetweb/civetweb/issues/94#issuecomment-204078333

### CODE REVIEW

**Comment by kainjow** [comment]
Just ran `make test` and it succeeds:

    100% tests passed, 0 tests failed out of 20

    Total Test time (real) =  10.71 sec

**Comment by kainjow** [comment]
I believe "gcc" on OS X on Travis is just an symlink to clang, so it's duplicate tests. It seems like Travis has GCC 4.8 for OS X, but I don't think many people use GCC on OS X nowadays. Clang is the compiler. But I'm not sure how to disable the GCC variant on Travis to reduce build time.

**Comment by bel2125** [comment]
Thank you for the fix. It seems now OSX builds work, and it was only one line in the build file you changed - probably easy if you know OSX and the build system.
Unfortunately I never used OSX and have no access to an OSX system to check the code there, and I never used CMake and check before.

Is it possible to store the result of the OSX build results, for the release?

**Comment by kainjow** [comment]
Seems like Travis can store the files, see:

https://docs.travis-ci.com/user/deployment/
https://docs.travis-ci.com/user/deployment/custom/

However I wouldn't, especially if you have no way to test the final binaries you copy out, and especially since Civetweb is primarily a developer library and not end-user program.

**Comment by bel2125** [comment]
> Civetweb is primarily a developer library and not end-user program.

It is used for both, developers and end users.

End users may download the binaries from https://sourceforge.net/projects/civetweb/files/
Up to 1.6 there was always a `.dmg` file for OSX. I have neither a way to build a `.dmg` file, nor a way to test it. Still, I don't want to cancel OS X support for end users.

The advantage for end users is, they can copy the executable and start the server with one click, without complicated setup and configuration. If you just want a http upload for files, or a simple html web page, you don`t need to do anything else. If you want more, you can use Lua (and now server side javascript). This is also used by end users.

You are right, I don't like to upload binaries that I can not test manually. But they are tested automatically by the CI tests. Probably we need a "civetweb OSX commissioner" to care OSX - I can't do it since I have no OSX system, and I've got enough to do anyway so I need to somehow limit the time spent dealing with curious properties of OSX.

**Comment by kainjow** [comment]
I noticed the Makefile.osx wasn't building correctly either. I'll look into integrating that functionality into CMake to reduce duplicate build code. We can also use CPack (part of CMake) for creating the OS X distribution file.

**Pull request merged**
