### PR TITLE
Resolve warnings

### PR DESCRIPTION
**Pull request by hahnjo**
Resolve compiler warnings with GCC 8.5.0 and Clang 13 (from CentOS 8):
 * Avoid pointer subtraction with null pointers
 * Remove unused `init` parameter of `mg_connect_client_impl`
 * Improve `const`-ness of options

### CODE REVIEW

**Comment by bel2125** [comment]
Please provide a description for every pull request: https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md#why-does-a-pull-request-need-a-description

**Comment by hahnjo** [comment]
> Please provide a description for every pull request: https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md#why-does-a-pull-request-need-a-description

Done

**Comment by bel2125** [comment]
Thank you.

- I can merge "Avoid pointer subtraction with null pointers"

- I don't want to merge [Remove unused init parameter of mg_connect_client_impl](https://github.com/civetweb/civetweb/pull/1056/commits/70b6b3ecfb20b2139a4bdec9788131c701eb311c), because this parameter will be used to resolve https://github.com/civetweb/civetweb/issues/479 and many associated issues (see there). It is true the parameter is currently unused, but not for very much longer. For the moment we can use a `(void)init;` to avoid a warning.

- In [Improve const-ness of options](https://github.com/civetweb/civetweb/pull/1056/commits/d0119c8a94c1ab2287ff24b839b85272659723dc) you essentially use a const cast to get rid of the const again before passing it to free in `start_civetweb` and `set_option`. I think we can merge this as well.

Can you modify your PR accordingly or should I cherry-pick the other two commits (haven't done that for a while, so I need to consult my GitHub cheat sheets again).

**Comment by hahnjo** [comment]
I've removed the second commit. Could have guessed that it's still work-in-progress, my bad.

**Comment by bel2125** [comment]
Thank you.
Merged.

**Pull request merged**
