### PR TITLE
Background script moved to external thread

### PR DESCRIPTION
**Pull request by BigJoe01**
Older behivor frezee fully the main thread.
Background script running in separeted thread, before main thread exit
send terminate signal to script. 

- Example added
- Check document my english is not well

### CODE REVIEW

**Comment by bel2125** [comment]
Thanks for your contribution.

I saw you created a new thread for the Lua background script.
Did you think about using a timer instead of a thread, like I did for Lua websockets:
https://github.com/civetweb/civetweb/blob/master/test/websocket.lua ?
`mg.set_timeout` can be used to register a timer callback to be called after some time, similar to [timer in javascript](https://www.w3schools.com/js/js_timing.asp). Also, you don't have to poll for "isterminated" but just have an optional "close" function defined.
This would make the programming model of a background script similar to the programming model for websockets.

Or is there a reason you need a real thread?

**Comment by BigJoe01** [comment]
Long running script
From my view point, the background script is a long running lua state, not a task based workflow. If i use internal timer solution, calling back running lua state from another thread is unsafe. Better option if we creating a new event driven background script.

Main thread vs external thread.
Usually mg_start called from application thread, long running script blocking application main thread, event driven like websocket only freeze for short time.
Cause high processor use.

**Comment by bel2125** [comment]
The current timer implementation uses one timer thread:
https://github.com/civetweb/civetweb/blob/master/src/timer.inl#L121

This thread can be used to call Lua functions:
https://github.com/civetweb/civetweb/blob/master/src/mod_lua.inl#L1392
It's safe as long as no other thread uses the same Lua state the same time.
The 'lua_action' uses a mutex for this.

**Comment by bel2125** [comment]
Sorry, I did not mean to criticize your pull request or frustrate you.
My only intention is to get the best programming model for background scripts, which fits to other programming models in the server and is not overly complex for maintenance.

I definitely want to merge the documentation (https://github.com/civetweb/civetweb/pull/508/commits/d388871e82886a5f44ac63bfb92e65f28ece05cf), and if a new thread turns out to be the best solution for a particular requirement it's also fine with me.

I just want to discuss all pull requests if they (1) modify or extend the [API](https://github.com/civetweb/civetweb/blob/master/docs/Contribution.md), (2) affect threading, (3) imply structural changes, (4) have significant influence for maintenance.

**Comment by BigJoe01** [comment]
Hello, not frustrate me. Next commit support timer based background script too.
I write another example for this work flow.

**Comment by bel2125** [comment]
> Hello, not frustrate me. Next commit support timer based background script too.
> I write another example for this work flow.

Glad to here that.
Need any help or further explanation of this mechanism?

**Comment by BigJoe01** [comment]
I saw how it works.

**Pull request closed without merging**
